### ISSUE TITLE
Getting this Error When Starting My Bot on the Latest Version

### ISSUE THREAD

**Issue by alima566** [theBowja/genshin-db#20]
```javascript
0|index  | Error: Cannot find module './data/image.min.json'
0|index  | Require stack:
0|index  | - /root/Bot/node_modules/genshin-db/src/main.js
0|index  | - /root/Bot/commands/genshin/character.js
0|index  | - /root/Bot/node_modules/wokcommands/dist/CommandHandler.js
0|index  | - /root/Bot/node_modules/wokcommands/dist/index.js
0|index  | - /root/Bot/index.js
0|index  |     at Function.Module._resolveFilename (internal/modules/cjs/loader.js:880:15)
0|index  |     at Function.Module._resolveFilename (/root/Bot/node_modules/module-alias/index.js:49:29)
0|index  |     at Module.Hook._require.Module.require (/usr/lib/node_modules/pm2/node_modules/require-in-the-middle/index.js:61:29)
0|index  |     at require (internal/modules/cjs/helpers.js:88:18)
0|index  |     at Object.<anonymous> (/root/Bot/node_modules/genshin-db/src/main.js:43:18)
0|index  |     at Module._compile (internal/modules/cjs/loader.js:1063:30)
0|index  |     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
0|index  |     at Module.load (internal/modules/cjs/loader.js:928:32)
0|index  |     at Function.Module._load (internal/modules/cjs/loader.js:769:14)
0|index  |     at Module.require (internal/modules/cjs/loader.js:952:19)
0|index  |     at Module.Hook._require.Module.require (/usr/lib/node_modules/pm2/node_modules/require-in-the-middle/index.js:80:39)
0|index  |     at require (internal/modules/cjs/helpers.js:88:18)
0|index  |     at Object.<anonymous> (/root/Bot/commands/genshin/character.js:1:17)
0|index  |     at Module._compile (internal/modules/cjs/loader.js:1063:30)
0|index  |     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
0|index  |     at Module.load (internal/modules/cjs/loader.js:928:32) {
0|index  |   code: 'MODULE_NOT_FOUND',
0|index  |   requireStack: [
0|index  |     '/root/Bot/node_modules/genshin-db/src/main.js',
0|index  |     '/root/Bot/commands/genshin/character.js',
0|index  |     '/root/Bot/node_modules/wokcommands/dist/CommandHandler.js',
0|index  |     '/root/Bot/node_modules/wokcommands/dist/index.js',
0|index  |     '/root/Bot/index.js'
0|index  |   ]
0|index  | }
0|index  | Error: Cannot find module './data/image.min.json'
0|index  | Require stack:
0|index  | - /root/Bot/node_modules/genshin-db/src/main.js
0|index  | - /root/Bot/commands/genshin/recipes.js
0|index  | - /root/Bot/node_modules/wokcommands/dist/CommandHandler.js
0|index  | - /root/Bot/node_modules/wokcommands/dist/index.js
0|index  | - /root/Bot/index.js
0|index  |     at Function.Module._resolveFilename (internal/modules/cjs/loader.js:880:15)
0|index  |     at Function.Module._resolveFilename (/root/Bot/node_modules/module-alias/index.js:49:29)
0|index  |     at Module.Hook._require.Module.require (/usr/lib/node_modules/pm2/node_modules/require-in-the-middle/index.js:61:29)
0|index  |     at require (internal/modules/cjs/helpers.js:88:18)
0|index  |     at Object.<anonymous> (/root/Bot/node_modules/genshin-db/src/main.js:43:18)
0|index  |     at Module._compile (internal/modules/cjs/loader.js:1063:30)
0|index  |     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
0|index  |     at Module.load (internal/modules/cjs/loader.js:928:32)
0|index  |     at Function.Module._load (internal/modules/cjs/loader.js:769:14)
0|index  |     at Module.require (internal/modules/cjs/loader.js:952:19)
0|index  |     at Module.Hook._require.Module.require (/usr/lib/node_modules/pm2/node_modules/require-in-the-middle/index.js:80:39)
0|index  |     at require (internal/modules/cjs/helpers.js:88:18)
0|index  |     at Object.<anonymous> (/root/Bot/commands/genshin/recipes.js:1:17)
0|index  |     at Module._compile (internal/modules/cjs/loader.js:1063:30)
0|index  |     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
0|index  |     at Module.load (internal/modules/cjs/loader.js:928:32) {
0|index  |   code: 'MODULE_NOT_FOUND',
0|index  |   requireStack: [
0|index  |     '/root/Bot/node_modules/genshin-db/src/main.js',
0|index  |     '/root/Bot/commands/genshin/recipes.js',
0|index  |     '/root/Bot/node_modules/wokcommands/dist/CommandHandler.js',
0|index  |     '/root/Bot/node_modules/wokcommands/dist/index.js',
0|index  |     '/root/Bot/index.js'
0|index  |   ]
0|index  | }
0|index  | Error: Cannot find module './data/image.min.json'
0|index  | Require stack:
0|index  | - /root/Bot/node_modules/genshin-db/src/main.js
0|index  | - /root/Bot/commands/genshin/weapon.js
0|index  | - /root/Bot/node_modules/wokcommands/dist/CommandHandler.js
0|index  | - /root/Bot/node_modules/wokcommands/dist/index.js
0|index  | - /root/Bot/index.js
0|index  |     at Function.Module._resolveFilename (internal/modules/cjs/loader.js:880:15)
0|index  |     at Function.Module._resolveFilename (/root/Bot/node_modules/module-alias/index.js:49:29)
0|index  |     at Module.Hook._require.Module.require (/usr/lib/node_modules/pm2/node_modules/require-in-the-middle/index.js:61:29)
0|index  |     at require (internal/modules/cjs/helpers.js:88:18)
0|index  |     at Object.<anonymous> (/root/Bot/node_modules/genshin-db/src/main.js:43:18)
0|index  |     at Module._compile (internal/modules/cjs/loader.js:1063:30)
0|index  |     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
0|index  |     at Module.load (internal/modules/cjs/loader.js:928:32)
0|index  |     at Function.Module._load (internal/modules/cjs/loader.js:769:14)
0|index  |     at Module.require (internal/modules/cjs/loader.js:952:19)
0|index  |     at Module.Hook._require.Module.require (/usr/lib/node_modules/pm2/node_modules/require-in-the-middle/index.js:80:39)
0|index  |     at require (internal/modules/cjs/helpers.js:88:18)
0|index  |     at Object.<anonymous> (/root/Bot/commands/genshin/weapon.js:1:17)
0|index  |     at Module._compile (internal/modules/cjs/loader.js:1063:30)
0|index  |     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
0|index  |     at Module.load (internal/modules/cjs/loader.js:928:32) {
0|index  |   code: 'MODULE_NOT_FOUND',
0|index  |   requireStack: [
0|index  |     '/root/Bot/node_modules/genshin-db/src/main.js',
0|index  |     '/root/Bot/commands/genshin/weapon.js',
0|index  |     '/root/Bot/node_modules/wokcommands/dist/CommandHandler.js',
0|index  |     '/root/Bot/node_modules/wokcommands/dist/index.js',
0|index  |     '/root/Bot/index.js'
0|index  |   ]
0|index  | }
```

**Comment by theBowja** [comment]
Can you tell me the specific version you have?

**Comment by theBowja** [comment]
I think this is a problem with v3.0.0.
Please update to v3.0.1 or v3.1.0.

Let me know if you still have issues.

**Comment by alima566** [comment]
That fixed the problem. Thanks.
