### ISSUE TITLE
Command failed: node ./generate.js 

### ISSUE THREAD

**Issue by NepPure** [theBowja/genshin-db#99]
_(:з」∠)_ help~~

```
% yarn run build
yarn run v1.22.4
$ node ./webpack/build.js
compiling index for data:
internal/modules/cjs/loader.js:960
  throw err;
  ^

Error: Cannot find module './data/ChineseSimplified/categories.json'
Require stack:
- /Users/owen/Git/genshin-card/src/generate.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:957:15)
    at Function.Module._load (internal/modules/cjs/loader.js:840:27)
    at Module.require (internal/modules/cjs/loader.js:1019:19)
    at require (internal/modules/cjs/helpers.js:77:18)
    at makeIndices (/Users/owen/Git/genshin-card/src/generate.js:66:20)
    at Object.<anonymous> (/Users/owen/Git/genshin-card/src/generate.js:59:1)
    at Module._compile (internal/modules/cjs/loader.js:1133:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1153:10)
    at Module.load (internal/modules/cjs/loader.js:977:32)
    at Function.Module._load (internal/modules/cjs/loader.js:877:14) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [ '/Users/owen/Git/genshin-card/src/generate.js' ]
}
child_process.js:669
    throw err;
    ^

Error: Command failed: node ./generate.js 
    at checkExecSyncError (child_process.js:630:11)
    at execSync (child_process.js:666:15)
    at Object.<anonymous> (/Users/owen/Git/genshin-card/webpack/build.js:31:1)
    at Module._compile (internal/modules/cjs/loader.js:1133:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1153:10)
    at Module.load (internal/modules/cjs/loader.js:977:32)
    at Function.Module._load (internal/modules/cjs/loader.js:877:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:74:12)
    at internal/main/run_main_module.js:18:47 {
  status: 1,
  signal: null,
  output: [ null, null, null ],
  pid: 5335,
  stdout: null,
  stderr: null
}
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

**Comment by theBowja** [comment]
Haha oops. I left in unused code

**Comment by NepPure** [comment]
hhhha I find it,

https://github.com/theBowja/genshin-db/blob/fe1d0b8325194db502a1cec18969a181fc0dfff0/src/generate.js#L66

Remove and everything works fine.
